### ISSUE TITLE
No proper message on server or API error

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#16]
No proper message on server or API error.

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-10 at 21 22 38](https://user-images.githubusercontent.com/65023866/194907535-355f4d53-6354-4203-9451-6094e0007904.png)

To reproduce this issue, change the URL to some wrong URL and run the app.

**Comment by UshaSaiC** [comment]
Added a custom server error message for above scenario
