### ISSUE TITLE
good to keep 1 space between just before open curly bracket. 

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#17]
good to keep 1 space between just before open curly bracket. 

https://github.com/UshaSaiC/MovieApp/blob/ca991c64fc7141fc34f1873770c4fb6ee5b37876/Movie/Views/MovieView.swift#L15

Try to integrate SwiftLint using SPM in the project. so that this kind of issues will get caught in compiler level & all contributors to this project will enforce to follow same coding conventions.

**Comment by UshaSaiC** [comment]
Got it. Updated the code base accordingly

**Comment by shebin-tw** [comment]
After pulling the latest code, I couldn't find SwiftLint in my end. did you added it?

**Comment by UshaSaiC** [comment]
Seems like my swiftlint had issues and somehow didn't get committed. Added the necessary files. Please have a look at it now. Adding on, there were some compile time issues highlighted by swiftlint which I have fixed parallelly

**Comment by shebin-tw** [comment]
Cool. awesome. i am able to see SwitLint in my end.
