### ISSUE TITLE
good to create MovieRatingsViewModel for MovieRatingsView & move the strings to viewModel

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#18]
good to create MovieRatingsViewModel for MovieRatingsView & move the strings to viewModel

https://github.com/UshaSaiC/MovieApp/blob/ca991c64fc7141fc34f1873770c4fb6ee5b37876/Movie/Views/MovieRatingsView.swift#L17

**Comment by UshaSaiC** [comment]
Moved it to MovieRatingsViewModel and called the value from MovieRatingsView
