### ISSUE TITLE
business logics should not present in view. suggesting move this logic from view to viewModel.

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#19]
business logics should not present in view. suggesting move this logic from view to viewModel.

https://github.com/UshaSaiC/MovieApp/blob/ca991c64fc7141fc34f1873770c4fb6ee5b37876/Movie/Views/StarsView.swift#L26

**Comment by UshaSaiC** [comment]
Done. Moved the logic to StarsViewModel
