### ISSUE TITLE
Keep in mind that usually baseURLs will keep in network related classes & endpoint will get append at network layer. However this project having only 1 REST API, so, its ok. 

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#20]
Keep in mind that usually baseURLs will keep in network related classes as a constant & endpoint will get append at network layer maybe when REST API invocation happens. However this project having only 1 REST API, so, its ok. 

https://github.com/UshaSaiC/MovieApp/blob/ca991c64fc7141fc34f1873770c4fb6ee5b37876/Movie/ViewModel/MovieViewModel.swift#L31

**Comment by UshaSaiC** [comment]
Moved the URL to a constant file
