### ISSUE TITLE
what is the intention behind keeping TextImageModifier inside a folder named "Identifier"? I am concerned about the folder name "Identifier".

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#23]
what is the intention behind keeping TextImageModifier inside a folder named "Identifier"? I am concerned about the folder name "Identifier".

**Comment by UshaSaiC** [comment]
Good catch. I renamed it as a modifier as its a custom modifier which is used at couple of places to format the text
