### ISSUE TITLE
its good to add gitignore file and avoid ".idea" folder 

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#33]
its good to add gitignore file and avoid ".idea" folder.
Also suggesting to remove ".idea" folder from repository.

**Comment by UshaSaiC** [comment]
Good catch. I did git add . and it got added as a chunk. Removed it now. Thanks for pointing it out

**Comment by shebin-tw** [comment]
add gitignore file in git repo, so others who is contributing to this project wont do the same mistake again :)
 
 We know no one else contributing, but just for your learnings.

**Comment by UshaSaiC** [comment]
Okay. Added the file having .idea folder for now
