### ISSUE TITLE
Can we write test cases for width calculation?

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#35]
Can we write test cases for width calculation?

https://github.com/UshaSaiC/MovieApp/blob/4f8c080ccc9a834c454158bdffe00f181f49d382/Movie/ViewModel/StarsViewModel.swift#L14

**Comment by UshaSaiC** [comment]
Okay. Added certain additional conditions wrt edge case values for rating parameters and updated TC's accordingly.
