### ISSUE TITLE
If i was developing this StarView, i will move rating into ViewModel with the following code.

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#39]
https://github.com/UshaSaiC/MovieApp/blob/4f8c080ccc9a834c454158bdffe00f181f49d382/Movie/Views/StarsView.swift#L12

If i was developing this StarView, i will move rating variable into ViewModel with the following code.

In View
```
@ObservedObject private var model: StarsViewModel
    
    init(rating: Double, viewModel: StarsViewModel? = nil) {
        _model = ObservedObject(wrappedValue: viewModel ?? StarsViewModel(rating: rating))
    }
```

In ViewModel

```
    let rating: Double
    
    init(rating: Double) {
        self.rating = rating
    }
```

**Comment by UshaSaiC** [comment]
Updated the code like below in stars view :
**self.model = model ?? StarsViewModel(rating: rating)**
instead of _model = ObservedObject(wrappedValue: viewModel ?? StarsViewModel(rating: rating))

Can you please let me know whats better in both options as look and feel wise both are working same

**Comment by shebin-tw** [comment]
There are some property wrappers like `StateObject` which wont allow 
`self.model = model ?? StarsViewModel(rating: rating)`
Thats why I did it in other way.

Since `ObservedObject` property wrapper is supporting `self.model = model ?? StarsViewModel(rating: rating)` we can keep it.

The intention of the issue is to keep all the variables in viewModel. here move `rating` variable to ViewModel.

**Comment by UshaSaiC** [comment]
Got it. Then will keep it as is

**Comment by shebin-tw** [comment]
I think you forgot to remove this line from View

https://github.com/UshaSaiC/MovieApp/blob/4b888a9f56079f2b5417f5bf4f2350a4e946dd43/Movie/Views/StarsView.swift#L12

**Comment by UshaSaiC** [comment]
Missed it. Done the removal of rating param
