### ISSUE TITLE
leading & trailing space is required. At present, the text is touching edge of the screen.

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#40]
leading & trailing space is required. At present, the text is touching edge of the screen.

![Simulator Screen Shot - iPhone 14 Pro - 2022-10-12 at 01 40 42](https://user-images.githubusercontent.com/65023866/195189336-e7a43005-8fb0-41c7-b7cf-8f163cf4cd9f.png)

**Comment by UshaSaiC** [comment]
Agreed. Updated the look and feel of error messages
