### ISSUE TITLE
Happy to see that you added gitignore file, however don't need to refer that file in Xcode Project

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#43]
Happy to see that you added gitignore file, however don't need to refer that file in Xcode Project. Because if you reference it in Xcode project, it will be part of bundle and it may include in ipa file. gitignore file is required at the development time, not intended to ship with ipa file.

<img width="273" alt="Screenshot 2022-10-12 at 10 48 12 AM" src="https://user-images.githubusercontent.com/65023866/195256326-0e0ff37b-61a4-4828-82e0-66794c22262e.png">

**Comment by UshaSaiC** [comment]
Okay, interesting to know this. Deleted the file from GitHub

**Comment by shebin-tw** [comment]
we have to keep in github
however we have to remove from Xcode.

**Comment by UshaSaiC** [comment]
I am adding the file on github. have a look and let me know if any missing

**Comment by shebin-tw** [comment]
@UshaSaiC  Still the file is referenced in Xcode, we have to remove that.

**Comment by UshaSaiC** [comment]
Thanks for the inputs. Pushed over the changes
