### ISSUE TITLE
images are stretched in landscape mode

### ISSUE THREAD

**Issue by shebin-tw** [UshaSaiC/MovieApp#7]
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-30 at 16 07 37](https://user-images.githubusercontent.com/65023866/193252449-83f04c96-539e-4d82-af80-6765833ce5ff.png)
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-30 at 16 07 41](https://user-images.githubusercontent.com/65023866/193252468-0c52076e-5055-4f52-b510-9411a19f0af5.png)
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-30 at 16 07 45](https://user-images.githubusercontent.com/65023866/193252480-74774927-30c7-47c3-97c7-9577f3f43df7.png)

**Comment by UshaSaiC** [comment]
Fixed the issue by using aspect ration as fit instead of fill
